### PR TITLE
Update POV on change

### PR DESCRIPTION
**Pull request by knownasilya**
POV would stick from previous streetview

### CODE REVIEW

**Comment by ybur-yug** [comment]
@knownasilya I'm not the right guy to review this but I dropped a Slack msg to our frontend team and I'm sure one of them will chime in and check it out when they have a chance.

Thanks, and happy hacking! :)

**Comment by ybur-yug** [comment]
CC @datajohnny @makobi or @carloscheddar

**Comment by FutoRicky** [comment]
Ah, I see. Nice find. @ybur-yug I got this 👍

**Comment by ybur-yug** [comment]
@FutoRicky I havent seen you in too long. Hope all is well :)

**Pull request merged**
